### ISSUE TITLE
CG Charter needs: Code of Conduct

### ISSUE THREAD

**Issue by bumblefudge** [swicg/potential-charters#15]
Currently just normrefs the [W3C-wide one](https://www.w3.org/Consortium/cepc/). Anyone wanna self-assign a PR to add or substract anything they think would be consensual in the CG?

**Comment by evanp** [comment]
We also need to reference the community group general communications policies:

https://www.w3.org/community/about/process/#general-policies

> All Participants agree to the following general communications policies:
>
> - Participants must have an identity within the community.
> - Communications must not be disruptive. Participants must refrain from defaming, harassing or otherwise offending other participants or their organizations.
> - Participants must not send unsolicited commercial messages or other promotional activities for personal matters or for third parties.
> - Participants must respect confidentiality levels of communications.

**Comment by bumblefudge** [comment]
I think the entirety of the Community Group Process is linked already on line 154!  But a good idea to direct people's attention to this specific section on friday's call maybe?

**Comment by evanp** [comment]
So, I'm not sure I understand the point here. The W3C COC and the Community Group Process are both referenced in the doc. Do we think there's a need for an additional COC above and beyond those two? Personally, I think it's plenty.

**Comment by bumblefudge** [comment]
Well, I opened the issue to see if anyone _else_ felt it _wasn't_ plenty-- a month passed, no one did, happy to reopen later if anyone wants to amend 😄
