### ISSUE TITLE
CG Charter needs: Scope definitions

### ISSUE THREAD

**Issue by bumblefudge** [swicg/potential-charters#16]
Remember, unlike a WG, we don't need to define INDIVIDUAL work items or task forces as in- or out-of-scope, just categories or scope areas.  Worth mentioning IP safety here, and red lines (i.e. places where we defer to other normative groups, which ones, etc).

Anyone wanna self-assign a PR to add or substract anything they think would be consensual in the CG?

**Comment by evanp** [comment]
I can try this one.
