### ISSUE TITLE
CG Charter Needs: A definition of a Task Force?

### ISSUE THREAD

**Issue by bumblefudge** [swicg/potential-charters#17]
Could be just a few sentences, no need to overthink this, BUT, that said, a second paragraph of non-normative stuff like suggestions or a github template for a TF repo with a readme with some sections to fill out would be awesome at some point... 🥺 👉 👈 

Anyone wanna self-assign a PR to add or substract anything they think would be consensual in the CG?

**Comment by evanp** [comment]
So, the staging doc and CG doc has a few notes around this area. I think there are some terms that we might want to unify or clarify:

- champion, "Committer", task force lead, report editor: these are all overlapping terms for "someone who is making sure a sub-project is happening". We could maybe tease apart "person organizing a project" from "person working on the document", though.
- repo, task force, report: We typically start a GitHub repository for making some kind of deliverable. I think that's always called a "report" in CG parlance, even if it's software.
