### ISSUE TITLE
Enable GitHub pages

### ISSUE THREAD

**Issue by evanp** [swicg/potential-charters#21]
It would be nice to view these charters on GitHub pages to make them easier to review.

**Comment by gobengo** [comment]
not against it. Perhaps there could be a tag here like triaged/needs-assignee

**Comment by dmitrizagidulin** [comment]
Enabling GH pages is just a button in the settings, no reason not to. I'll enable it now.

**Comment by dmitrizagidulin** [comment]
Ok, anything merged to `main` is now served on Github pages (after the usual propagation delay).

Feel free to close the issue (unless you meant setting up previews as a Github action on PRs, in which case -- I agree with what @gobengo said, that's a more involved process.

**Comment by evanp** [comment]
This seems done!
