### ISSUE TITLE
Number of chairs in CG Charter

### ISSUE THREAD

**Issue by evanp** [swicg/potential-charters#31]
The charter doesn't define how many chairs we should have.

In the past we have had 2 or 3 (I think).

**Comment by gobengo** [comment]
I think it is a feature that the CG Charter doesn't specify a fixed number. It's a chair's decision. There's no right answer IMHO. IMHO it is good that the current draft cg charter allows this to vary, i.e. number of co-chairs is the elected chair's decision. Chairs can run for election and differentiate based on their co-chair selection strategy including number of co-chairs. i.e. let's do nothing here and retain the affordance for voters to decide number of cochairs, not the charter

**Comment by dmitrizagidulin** [comment]
Agreed, I think 3 chairs is a good number to aim for, but maybe not worth it putting it into the charter.

**Comment by evanp** [comment]
I disagree. I'd like to see a fixed number. Two seems enough.

**Comment by evanp** [comment]
The charter now says 1-3, which I think is good.
