### ISSUE TITLE
Method of choosing chairs in CG Charter

### ISSUE THREAD

**Issue by evanp** [swicg/potential-charters#32]
The boilerplate in the CG Charter says:

> Participants in this group choose their Chair(s) and can replace their Chair(s) at any time using whatever means they prefer. 

It then lists out an election process, which seems like a pretty straightforward way to choose chairs.

I think we should just accept this election process as the "means we prefer".

One thing it doesn't define is what happens when a Chair leaves their job. It might be nice to call that out.

Another thing it doesn't define is what happens if participation dips below 5 people. I think that's unlikely, but we could maybe say something like "If 5 participants, or a majority of participants, ..."

**Comment by gobengo** [comment]
> Another thing it doesn't define is what happens if participation dips below 5 people. I think that's unlikely, but we could maybe say something like "If 5 participants, or a majority of participants, ..."

Is this something you've seen other charters call out? What brought it to mind?

In general I'm fine with no explicit text on this, and trust w3c community team to call for participation and/or disband the group. But it seems unlikely to happen any time soon.

**Comment by evanp** [comment]
> Is this something you've seen other charters call out?

I don't read a lot of charters. This one calls out a particular number, though.

> What brought it to mind?

Well, I was reading the charter, and there was the number 5, and I thought, "Is that the right number? Is it too high or low?"

Second, this CG's active participation has dropped pretty low before.

Let's add it in just in case.

**Comment by csarven** [comment]
The W3C CG process already covers the [Grounds for Closure of a Community Group](https://www.w3.org/community/about/process/#closure).

https://www.w3.org/community/about/faq/#close-inactive

>From time to time W3C closes inactive groups, in part to make it easier for the community to find active groups. Per the [Community Group process](https://www.w3.org/community/about/agreements/), a group is deemed inactive if there are fewer than 3 participants, if there are no chairs, or if there does not appear to be any activity in the group (e.g., email or activity in known GitHub repositories) within the past six months.

>Ten (10) days before closing a group for inactivity, W3C alerts the group participants. Group participants may petition to keep the group open, but must provide rationale for doing so.

**Comment by evanp** [comment]
I don't know if a PR was merged that I hadn't seen, or if there was just a section I wasn't reading, but there is now a section on selecting and removing chairs, so I think we're good here.
