### ISSUE TITLE
Stopping at CG Report level in staging proposal

### ISSUE THREAD

**Issue by evanp** [swicg/potential-charters#35]
Not all work in the CG needs to become a W3C Recommendation. Is it clear that some work will just stop at Stage 2 (CG report) and not move on to a Recommendation?

**Comment by gobengo** [comment]
yes

**Comment by dmitrizagidulin** [comment]
I think this is implied by the current text? (that work only advances to each next stage if there's a demand and the prerequisites are fulfilled). Feel free to make a PR to add that wording, though.
