### ISSUE TITLE
AP-only scope for WG: no related notes

### ISSUE THREAD

**Issue by evanp** [swicg/potential-charters#38]
The scope in the AP-only WG charter says "as well as related Notes". I don't think we have any related Notes.

**Comment by gobengo** [comment]
Looks like it is twice here https://github.com/swicg/potential-charters/blob/main/ap-maintenance-wg-charter.html#L81

What do you want to see to resolve the issue?
It seems like an observation.
I'd support the removal of the quoted text if it was a PR.

otoh I also think it'd be fine to leave it in. One could interpret it as allowing the WG to publish Notes, which I don't think is inherently a bad idea. Do you want the charter to forbid working on any Notes?

**Comment by evanp** [comment]
If this is a maintenance-only wg, we should take out "Notes" because there are no Notes to maintain.

If it's not a maintenance-only wg, we should allow it to create Notes, yes.

**Comment by bumblefudge** [comment]
(nit: i find this last commit convincing re: net-new Notes, but can a maintenance-only WG maintain... existing Notes of the CG or related non-normative outputs of the previous WG?)

**Comment by evanp** [comment]
I just realized that there *is* a Note related to AP:

https://www.w3.org/TR/social-web-protocols/

So, I'm going to close this.
