### ISSUE TITLE
Review CG charter to make sure it's compatible with staging process

### ISSUE THREAD

**Issue by evanp** [swicg/potential-charters#6]
I think this process is important; we should probably make sure that the charter proposal is compatible.

**Comment by bumblefudge** [comment]
I don't think anything in today's version of the template would clash with it, but how the "scope" section and "task forces" section get written might? i'd say keep this open until the CG is almost done and check again at the end of the CG PR-a-thon.

**Comment by bumblefudge** [comment]
Oh that reminds me-- currently the `stage-process.md` is just kinda hanging out in this repo; the CG charter and/or WG charter need to refer to it explicitly. PRs welcome!

**Comment by evanp** [comment]
I think this is the case, and we can close it.
